export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  tags: string[];
  author: string;
  categoryId: string;
  featured: boolean;
}

export const articles: Article[] = [
  // Featured Article
  {
    slug: "ai-trends-2025-2026",
    title: "2025-2026年AI技术趋势深度解析：从大模型到智能体的范式革命",
    excerpt: "从DeepSeek R1的推理突破到AI Agent的全面爆发，从GPT-5的多模态融合到国产大模型的集体崛起，全面解读当前AI领域的核心技术趋势与产业变革。",
    date: "2026-05-04",
    tags: ["AI趋势", "大模型", "AI Agent", "多模态", "DeepSeek", "GPT-5"],
    author: "BigAI",
    categoryId: "llm",
    featured: true,
  },
  // LLM Articles
  {
    slug: "llm-001-gpt5-release",
    title: "GPT-5发布：原生多模态的新纪元",
    excerpt: "OpenAI发布GPT-5，标志着大语言模型进入原生多模态时代，在推理、代码、多语言等方面实现全面跃升，重新定义了AI能力的边界。",
    date: "2026-05-05",
    tags: ["GPT-5", "OpenAI", "多模态", "大模型"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-002-deepseek-r1-breakthrough",
    title: "DeepSeek R1突破：打破规模神话的推理革命",
    excerpt: "中国AI公司DeepSeek发布的R1推理模型，以约600万美元的训练成本实现了与OpenAI o1相当的推理性能，彻底打破了行业迷思。",
    date: "2026-05-05",
    tags: ["DeepSeek R1", "推理模型", "国产大模型", "AI突破"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-003-claude4-anthropic",
    title: "Claude 4：Anthropic的安全优先AI哲学",
    excerpt: "Anthropic发布Claude 4，在保持安全优先理念的同时，实现了性能的大幅提升，为AI安全发展提供了新的范式。",
    date: "2026-05-04",
    tags: ["Claude 4", "Anthropic", "AI安全", "Constitutional AI"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-004-gemini2-google",
    title: "Gemini 2.0：Google的多模态AI战略",
    excerpt: "Google发布Gemini 2.0，标志着其在多模态AI领域的全面发力，整合搜索、云服务和硬件生态，构建完整的AI战略版图。",
    date: "2026-05-04",
    tags: ["Gemini 2.0", "Google", "多模态AI", "AI战略"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-005-deepseek-v4-open",
    title: "DeepSeek V4开源：国产大模型的全栈突破",
    excerpt: "DeepSeek发布V4模型并全面开源，在编程、世界知识和逻辑推理方面表现优异，标志着国产大模型在综合能力上达到全球第一梯队水平。",
    date: "2026-05-03",
    tags: ["DeepSeek V4", "开源大模型", "国产AI", "全栈国产化"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-006-llama4-meta",
    title: "Llama 4：Meta的开源AI战略",
    excerpt: "Meta发布Llama 4，继续推进开源AI战略，为全球开发者和企业提供强大的开源大模型选择。",
    date: "2026-05-03",
    tags: ["Llama 4", "Meta", "开源AI", "大模型"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-007-qwen35-alibaba",
    title: "Qwen 3.5：阿里巴巴的大模型生态战略",
    excerpt: "阿里巴巴发布Qwen 3.5，整合电商、云计算和企业服务生态，构建完整的AI应用版图。",
    date: "2026-05-02",
    tags: ["Qwen 3.5", "阿里巴巴", "大模型生态", "电商AI"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-008-reasoning-models",
    title: "推理模型：AI的深度思考能力",
    excerpt: "推理模型成为2025年AI发展的核心方向，OpenAI o1、DeepSeek R1等模型展示了AI思考的新范式。",
    date: "2026-05-02",
    tags: ["推理模型", "AI推理", "思维链", "o1"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-009-moe-architecture",
    title: "MoE架构：大模型的效率革命",
    excerpt: "混合专家（MoE）架构成为大模型的主流选择，在模型容量和推理效率之间实现最佳平衡。",
    date: "2026-05-01",
    tags: ["MoE架构", "混合专家", "模型效率", "大模型架构"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-010-small-models",
    title: "小模型崛起：AI的边缘革命",
    excerpt: "小模型（SLM）正在崛起，以更低的成本和更高的效率满足边缘计算和实时应用需求。",
    date: "2026-05-01",
    tags: ["小模型", "SLM", "边缘计算", "AI效率"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-011-long-context",
    title: "长上下文：AI的记忆革命",
    excerpt: "长上下文能力成为大模型的核心竞争力，从4K到1M+ token的突破正在改变AI应用的方式。",
    date: "2026-04-30",
    tags: ["长上下文", "上下文窗口", "AI记忆", "大模型"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-013-rag-technology",
    title: "RAG技术：让AI拥有知识库",
    excerpt: "检索增强生成（RAG）技术成为企业AI应用的核心架构，让大模型能够利用外部知识库提供准确答案。",
    date: "2026-04-30",
    tags: ["RAG", "检索增强生成", "知识库", "企业AI"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-015-model-evaluation",
    title: "模型评估：如何衡量AI的真实能力",
    excerpt: "模型评估成为AI发展的关键环节，从基准测试到人类评估，建立科学的能力衡量体系。",
    date: "2026-04-29",
    tags: ["模型评估", "基准测试", "AI能力", "评估方法"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-017-code-models",
    title: "代码模型：AI程序员的崛起",
    excerpt: "代码生成模型成为AI应用最成功的领域之一，正在改变软件开发的方式。",
    date: "2026-04-29",
    tags: ["代码模型", "AI编程", "GitHub Copilot", "软件开发"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  {
    slug: "llm-020-open-source-ecosystem",
    title: "开源生态：AI民主化的推动力",
    excerpt: "开源AI生态正在蓬勃发展，从模型到工具到应用，构建完整的技术栈，推动AI技术的民主化。",
    date: "2026-04-28",
    tags: ["开源AI", "AI民主化", "开源生态", "Hugging Face"],
    author: "BigAI",
    categoryId: "llm",
    featured: false,
  },
  // Agent Articles
  {
    slug: "agent-001-mcp-protocol",
    title: "MCP协议：AI Agent的互操作标准",
    excerpt: "Anthropic推出的MCP（Model Context Protocol）成为AI Agent工具调用的开放标准，获得业界广泛支持，正在成为AI Agent基础设施的核心组件。",
    date: "2026-05-05",
    tags: ["MCP协议", "AI Agent", "工具调用", "开放标准"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-002-devin-ai-coder",
    title: "Devin：首个AI软件工程师",
    excerpt: "Cognition AI发布的Devin被誉为首个AI软件工程师，能够独立完成复杂的软件开发任务，标志着AI Agent进入新阶段。",
    date: "2026-05-05",
    tags: ["Devin", "AI程序员", "软件工程师", "AI Agent"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-003-cursor-ai-ide",
    title: "Cursor AI IDE：重新定义代码编辑器",
    excerpt: "Cursor以其深度AI集成和卓越的用户体验，正在成为开发者的首选IDE，重新定义了代码编辑器的形态。",
    date: "2026-05-04",
    tags: ["Cursor", "AI IDE", "代码编辑器", "开发工具"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-004-multi-agent-collaboration",
    title: "多Agent协作：AI的团队工作模式",
    excerpt: "多Agent协作成为AI应用的新范式，多个AI Agent协同工作，解决复杂问题，实现超越单一Agent的能力。",
    date: "2026-05-04",
    tags: ["多Agent", "Agent协作", "AI团队", "AutoGen"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-005-a2a-communication",
    title: "A2A通信：Agent之间的对话协议",
    excerpt: "Agent-to-Agent（A2A）通信成为AI Agent协作的基础设施，定义了Agent之间交换信息和协调行动的标准。",
    date: "2026-05-03",
    tags: ["A2A通信", "Agent协议", "AI协作", "通信标准"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-006-enterprise-agents",
    title: "企业级Agent：AI赋能企业运营",
    excerpt: "企业级Agent正在改变企业运营方式，从客服到销售到运营，AI Agent正在成为企业数字化转型的重要工具。",
    date: "2026-05-03",
    tags: ["企业Agent", "数字化转型", "AI运营", "智能客服"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-008-langchain-framework",
    title: "LangChain：AI应用开发的标准框架",
    excerpt: "LangChain成为AI应用开发的事实标准框架，提供了从模型调用到Agent构建的完整工具链。",
    date: "2026-05-02",
    tags: ["LangChain", "AI框架", "应用开发", "开源"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-009-crewai-platform",
    title: "CrewAI：简洁的多Agent框架",
    excerpt: "CrewAI以其简洁的API设计和强大的多Agent协作能力，成为构建AI团队的热门选择。",
    date: "2026-05-02",
    tags: ["CrewAI", "多Agent框架", "AI团队", "开源"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-010-autogen-microsoft",
    title: "AutoGen：微软的多Agent框架",
    excerpt: "微软的AutoGen框架以其强大的多Agent对话能力和灵活的架构，成为构建复杂AI系统的首选工具。",
    date: "2026-05-01",
    tags: ["AutoGen", "微软", "多Agent", "AI框架"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-011-agent-memory",
    title: "Agent记忆：AI的长期记忆系统",
    excerpt: "Agent记忆系统是AI Agent实现长期交互和个性化服务的关键技术，让Agent能够记住用户偏好和历史交互。",
    date: "2026-05-01",
    tags: ["Agent记忆", "长期记忆", "个性化", "AI系统"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-012-tool-calling",
    title: "工具调用：Agent的能力扩展",
    excerpt: "工具调用（Tool Calling）是AI Agent扩展能力的关键机制，让Agent能够执行代码、访问API、操作外部系统。",
    date: "2026-04-30",
    tags: ["工具调用", "Function Calling", "Agent能力", "API"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-014-customer-service-agent",
    title: "智能客服Agent：重新定义客户服务",
    excerpt: "智能客服Agent正在改变客户服务行业，从简单的问答机器人进化为能够处理复杂问题的智能助手。",
    date: "2026-04-30",
    tags: ["智能客服", "客户服务", "AI客服", "企业应用"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-017-personal-assistant",
    title: "个人助手Agent：AI时代的私人助理",
    excerpt: "个人助手Agent正在成为每个人的AI伙伴，从日程管理到信息检索，提供全方位的个人服务。",
    date: "2026-04-29",
    tags: ["个人助手", "AI助理", "Siri", "智能助手"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-019-medical-agent",
    title: "医疗Agent：AI辅助诊疗的新时代",
    excerpt: "医疗Agent正在改变医疗行业，从辅助诊断到患者管理，为医生和患者提供智能支持。",
    date: "2026-04-29",
    tags: ["医疗Agent", "AI医疗", "辅助诊断", "智慧医疗"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  {
    slug: "agent-020-education-agent",
    title: "教育Agent：个性化学习的新时代",
    excerpt: "教育Agent正在改变教育方式，从个性化学习到智能辅导，为学生和教育者提供全新的教育体验。",
    date: "2026-04-28",
    tags: ["教育Agent", "个性化学习", "智能辅导", "AI教育"],
    author: "BigAI",
    categoryId: "agent",
    featured: false,
  },
  // Multimodal Articles
  {
    slug: "multimodal-001-sora-video",
    title: "Sora视频生成：OpenAI的视频革命",
    excerpt: "OpenAI发布的Sora视频生成模型，能够根据文本描述生成高质量视频，标志着AI视频生成进入新纪元。",
    date: "2026-05-05",
    tags: ["Sora", "视频生成", "OpenAI", "AI视频"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-002-kling-video",
    title: "可灵视频：国产AI视频生成的突破",
    excerpt: "快手推出的可灵视频生成模型，在视频质量和生成效率上取得重大突破，成为国产AI视频生成的代表。",
    date: "2026-05-05",
    tags: ["可灵", "视频生成", "快手", "国产AI"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-003-midjourney-v7",
    title: "Midjourney V7：AI绘画的新高度",
    excerpt: "Midjourney发布V7版本，在图像质量、细节控制和风格多样性上实现全面突破，巩固了其在AI绘画领域的领先地位。",
    date: "2026-05-04",
    tags: ["Midjourney", "AI绘画", "图像生成", "V7"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-004-dalle4",
    title: "DALL-E 4：OpenAI的图像生成进化",
    excerpt: "OpenAI发布DALL-E 4，在图像生成质量、文本理解和编辑能力上实现显著提升，为创意工作者提供强大工具。",
    date: "2026-05-04",
    tags: ["DALL-E 4", "OpenAI", "图像生成", "AI绘画"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-005-stable-diffusion4",
    title: "Stable Diffusion 4：开源图像生成的新标杆",
    excerpt: "Stability AI发布Stable Diffusion 4，在保持开源优势的同时，图像质量达到商业产品水平。",
    date: "2026-05-03",
    tags: ["Stable Diffusion", "开源AI", "图像生成", "SD4"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-006-whisper-voice",
    title: "Whisper语音识别：AI听懂世界",
    excerpt: "OpenAI的Whisper语音识别模型，以接近人类的准确率支持近百种语言，成为语音AI的基础设施。",
    date: "2026-05-03",
    tags: ["Whisper", "语音识别", "OpenAI", "多语言"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-007-elevenlabs",
    title: "ElevenLabs：AI语音合成的领导者",
    excerpt: "ElevenLabs以其逼真的AI语音合成技术，正在改变内容创作、游戏配音和有声书等领域。",
    date: "2026-05-02",
    tags: ["ElevenLabs", "语音合成", "AI配音", "TTS"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-008-suno-music",
    title: "Suno音乐生成：AI作曲的新时代",
    excerpt: "Suno的AI音乐生成技术，让普通人也能创作专业水准的音乐，正在改变音乐创作的方式。",
    date: "2026-05-02",
    tags: ["Suno", "AI音乐", "音乐生成", "AI作曲"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-010-3d-generation",
    title: "AI 3D生成：从文字到三维世界",
    excerpt: "AI 3D生成技术快速发展，从文本描述直接生成3D模型，正在改变游戏、建筑和产品设计等行业。",
    date: "2026-05-01",
    tags: ["3D生成", "AI建模", "三维设计", "游戏开发"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-011-realtime-translation",
    title: "实时翻译：打破语言障碍的AI",
    excerpt: "AI实时翻译技术日趋成熟，支持近百种语言的即时互译，正在改变国际交流和跨国业务。",
    date: "2026-05-01",
    tags: ["实时翻译", "AI翻译", "多语言", "国际交流"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-012-medical-imaging",
    title: "AI医学影像：智能诊断的眼睛",
    excerpt: "AI医学影像分析技术在CT、MRI、X光等领域广泛应用，辅助医生提高诊断准确率和效率。",
    date: "2026-04-30",
    tags: ["医学影像", "AI诊断", "医疗AI", "影像分析"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-013-autonomous-driving",
    title: "自动驾驶视觉：AI驱动的出行革命",
    excerpt: "自动驾驶的视觉感知技术持续进步，从L2到L4的演进正在重塑未来出行方式。",
    date: "2026-04-30",
    tags: ["自动驾驶", "视觉感知", "AI出行", "智能汽车"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-015-digital-human",
    title: "数字人：AI驱动的虚拟形象",
    excerpt: "数字人技术快速发展，从虚拟主播到企业代言人，AI驱动的虚拟形象正在进入各行各业。",
    date: "2026-04-29",
    tags: ["数字人", "虚拟形象", "AI主播", "元宇宙"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-016-ai-design-tools",
    title: "AI设计工具：创意工作的革命",
    excerpt: "AI设计工具正在改变设计师的工作方式，从UI设计到品牌设计，AI成为创意工作者的得力助手。",
    date: "2026-04-29",
    tags: ["AI设计", "设计工具", "创意AI", "UI设计"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  {
    slug: "multimodal-020-document-ai",
    title: "文档AI：智能文档处理的新时代",
    excerpt: "文档AI技术让机器能够理解、分析和生成各类文档，正在改变企业的文档处理流程。",
    date: "2026-04-28",
    tags: ["文档AI", "智能文档", "OCR", "企业应用"],
    author: "BigAI",
    categoryId: "multimodal",
    featured: false,
  },
  // News Articles
  {
    slug: "news-001-openai-funding-2025",
    title: "OpenAI融资：AI独角兽的资本之路",
    excerpt: "OpenAI完成新一轮巨额融资，估值突破新高，反映了资本市场对AI领域的持续看好。",
    date: "2026-05-05",
    tags: ["OpenAI", "融资", "AI投资", "独角兽"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-002-nvidia-ai-chip",
    title: "NVIDIA AI芯片：算力霸主的持续扩张",
    excerpt: "NVIDIA发布新一代AI芯片，巩固其在AI算力领域的霸主地位，推动AI基础设施升级。",
    date: "2026-05-05",
    tags: ["NVIDIA", "AI芯片", "GPU", "算力"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-003-china-ai-regulation",
    title: "中国AI监管：平衡创新与安全",
    excerpt: "中国持续完善AI监管体系，在促进AI发展的同时确保技术安全和可控。",
    date: "2026-05-04",
    tags: ["AI监管", "中国政策", "AI安全", "合规"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-004-eu-ai-act",
    title: "欧盟AI法案：全球AI治理的风向标",
    excerpt: "欧盟AI法案正式实施，成为全球首个全面的AI监管法规，对全球AI治理产生深远影响。",
    date: "2026-05-04",
    tags: ["欧盟AI法案", "AI监管", "全球治理", "合规"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-005-google-ai-strategy",
    title: "Google AI战略：搜索巨头的全面转型",
    excerpt: "Google全面押注AI，从搜索到云服务，从硬件到软件，AI成为Google的核心战略。",
    date: "2026-05-03",
    tags: ["Google", "AI战略", "搜索", "云计算"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-007-apple-ai-intelligence",
    title: "Apple Intelligence：苹果的AI布局",
    excerpt: "苹果推出Apple Intelligence，将AI深度整合到iPhone、Mac等设备，定义端侧AI新标准。",
    date: "2026-05-03",
    tags: ["Apple", "Apple Intelligence", "端侧AI", "iPhone"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-008-microsoft-copilot",
    title: "Microsoft Copilot：AI赋能办公",
    excerpt: "微软Copilot全面升级，将AI能力深度整合到Office全家桶，重新定义办公软件。",
    date: "2026-05-02",
    tags: ["Microsoft", "Copilot", "AI办公", "Office"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-009-bytedance-ai",
    title: "字节跳动AI：内容巨头的AI转型",
    excerpt: "字节跳动全面拥抱AI，从内容推荐到内容创作，AI正在重塑这家内容巨头的核心竞争力。",
    date: "2026-05-02",
    tags: ["字节跳动", "AI内容", "推荐算法", "内容创作"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-012-ai-startup-wave",
    title: "AI创业浪潮：新独角兽的崛起",
    excerpt: "AI创业持续火热，一批新独角兽快速崛起，覆盖大模型、Agent、应用等各个领域。",
    date: "2026-05-01",
    tags: ["AI创业", "独角兽", "创业投资", "AI公司"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-013-ai-copyright",
    title: "AI版权争议：创作权的边界",
    excerpt: "AI生成内容的版权问题引发广泛讨论，法律界正在探索AI时代的版权保护新框架。",
    date: "2026-05-01",
    tags: ["AI版权", "知识产权", "AI创作", "法律"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-015-ai-job-impact",
    title: "AI与就业：技术变革下的职场",
    excerpt: "AI正在深刻影响就业市场，一些岗位消失，新岗位涌现，职场人需要适应这一变革。",
    date: "2026-04-30",
    tags: ["AI就业", "职场变革", "技能转型", "劳动力"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-016-ai-china-domestic",
    title: "国产AI崛起：中国AI产业全景",
    excerpt: "中国AI产业快速发展，从芯片到模型到应用，国产替代正在全面推进。",
    date: "2026-04-30",
    tags: ["国产AI", "中国AI", "AI产业", "国产替代"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-017-ai-talent-war",
    title: "AI人才争夺战：顶尖人才的稀缺",
    excerpt: "AI人才供不应求，各大公司展开激烈的人才争夺，薪资水平持续攀升。",
    date: "2026-04-29",
    tags: ["AI人才", "人才争夺", "薪资", "招聘"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-019-open-source-ai",
    title: "开源AI运动：技术民主化的力量",
    excerpt: "开源AI持续发展，从模型到工具到框架，开源正在推动AI技术的民主化。",
    date: "2026-04-29",
    tags: ["开源AI", "技术民主化", "开源模型", "社区"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  {
    slug: "news-020-ai-industry-report",
    title: "AI产业报告：行业全景与发展趋势",
    excerpt: "最新AI产业报告揭示行业发展趋势，从技术突破到商业落地，全面解读AI产业现状。",
    date: "2026-04-28",
    tags: ["AI产业", "行业报告", "发展趋势", "市场分析"],
    author: "BigAI",
    categoryId: "news",
    featured: false,
  },
  // Frontier Articles
  {
    slug: "frontier-001-tesla-optimus",
    title: "Tesla Optimus：人形机器人的商业化之路",
    excerpt: "特斯拉的Optimus人形机器人持续迭代，正在从概念走向量产，开启人形机器人商业化时代。",
    date: "2026-05-05",
    tags: ["Tesla Optimus", "人形机器人", "特斯拉", "机器人"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-002-figure-ai",
    title: "Figure AI：人形机器人的新势力",
    excerpt: "Figure AI以创新的人形机器人设计获得巨额融资，成为人形机器人领域的新势力。",
    date: "2026-05-05",
    tags: ["Figure AI", "人形机器人", "机器人创业", "AI硬件"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-003-unitree-robot",
    title: "宇树机器人：国产机器人的崛起",
    excerpt: "宇树科技的四足机器人和人形机器人产品走向全球，代表国产机器人的崛起。",
    date: "2026-05-04",
    tags: ["宇树", "四足机器人", "国产机器人", "机器人"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-004-quantum-google",
    title: "Google量子计算：量子霸权的探索",
    excerpt: "Google持续推动量子计算研究，在量子霸权和量子纠错方面取得重要进展。",
    date: "2026-05-04",
    tags: ["量子计算", "Google", "量子霸权", "前沿科技"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-005-quantum-china",
    title: "中国量子计算：追赶与突破",
    excerpt: "中国在量子计算领域快速追赶，从量子通信到量子计算，取得一系列重要突破。",
    date: "2026-05-03",
    tags: ["量子计算", "中国科技", "量子通信", "前沿科技"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-006-neuralink-bci",
    title: "Neuralink脑机接口：人机融合的未来",
    excerpt: "Neuralink的脑机接口技术持续突破，正在从实验室走向临床应用，开启人机融合新时代。",
    date: "2026-05-03",
    tags: ["Neuralink", "脑机接口", "BCI", "马斯克"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-007-nuclear-fusion",
    title: "核聚变能源：清洁能源的终极梦想",
    excerpt: "核聚变研究取得重要进展，商业化核聚变发电正在从梦想走向现实。",
    date: "2026-05-02",
    tags: ["核聚变", "清洁能源", "前沿科技", "能源革命"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-008-spacex-starship",
    title: "SpaceX星舰：太空探索的新纪元",
    excerpt: "SpaceX的星舰火箭持续测试迭代，正在开启太空探索和商业航天的新纪元。",
    date: "2026-05-02",
    tags: ["SpaceX", "星舰", "太空探索", "马斯克"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-009-china-space",
    title: "中国航天：太空探索的中国力量",
    excerpt: "中国航天事业持续发展，从空间站到月球探测，展现中国太空探索的实力。",
    date: "2026-05-01",
    tags: ["中国航天", "太空探索", "空间站", "月球探测"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-011-crispr-gene",
    title: "CRISPR基因编辑：生命科学的革命",
    excerpt: "CRISPR基因编辑技术持续发展，从基础研究到临床应用，正在改变医学和农业。",
    date: "2026-05-01",
    tags: ["CRISPR", "基因编辑", "生命科学", "生物技术"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-012-solid-state-battery",
    title: "固态电池：下一代能源存储",
    excerpt: "固态电池技术取得突破，更高的能量密度和安全性将改变电动汽车和储能行业。",
    date: "2026-04-30",
    tags: ["固态电池", "电池技术", "电动汽车", "能源存储"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-013-6g-communication",
    title: "6G通信：下一代移动网络",
    excerpt: "6G通信技术研发加速，将带来更快的速度、更低的延迟和更广的连接。",
    date: "2026-04-30",
    tags: ["6G", "通信技术", "移动网络", "前沿科技"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-014-brain-chip",
    title: "脑芯片：神经形态计算的未来",
    excerpt: "脑芯片技术发展，将类脑计算带入现实，为AI计算提供新的硬件范式。",
    date: "2026-04-29",
    tags: ["脑芯片", "神经形态计算", "类脑计算", "AI芯片"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-015-synthetic-biology",
    title: "合成生物学：重新设计生命",
    excerpt: "合成生物学快速发展，从生物制造到医疗健康，正在重新定义生命科学的边界。",
    date: "2026-04-29",
    tags: ["合成生物学", "生物制造", "生命科学", "前沿科技"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  {
    slug: "frontier-020-web3-ai",
    title: "Web3与AI：去中心化的智能未来",
    excerpt: "Web3与AI的融合正在创造新的可能性，去中心化AI成为新的技术探索方向。",
    date: "2026-04-28",
    tags: ["Web3", "去中心化AI", "区块链", "AI融合"],
    author: "BigAI",
    categoryId: "frontier",
    featured: false,
  },
  // Reports Articles
  {
    slug: "reports-001-ai-trends-2026",
    title: "2026年AI趋势报告：技术演进与产业变革",
    excerpt: "全面解读2026年AI领域的技术趋势、产业变革和投资机会，为决策者提供战略参考。",
    date: "2026-05-05",
    tags: ["AI趋势", "2026报告", "技术演进", "产业分析"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-002-llm-landscape",
    title: "大模型全景报告：竞争格局与技术路线",
    excerpt: "深度分析大模型领域的竞争格局、技术路线和商业化进展，揭示行业发展趋势。",
    date: "2026-05-05",
    tags: ["大模型", "竞争格局", "技术路线", "行业报告"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-003-agent-market",
    title: "AI Agent市场报告：爆发前夜的新蓝海",
    excerpt: "AI Agent市场正在爆发，本报告分析市场规模、竞争格局和投资机会。",
    date: "2026-05-04",
    tags: ["AI Agent", "市场报告", "投资机会", "行业分析"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-004-multimodal-market",
    title: "多模态AI市场报告：跨模态融合的商业价值",
    excerpt: "多模态AI市场快速增长，本报告分析技术进展、应用场景和市场机会。",
    date: "2026-05-04",
    tags: ["多模态AI", "市场报告", "跨模态", "商业价值"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-005-china-ai-industry",
    title: "中国AI产业报告：国产替代与自主创新",
    excerpt: "中国AI产业快速发展，本报告分析国产替代进程、创新能力和产业生态。",
    date: "2026-05-03",
    tags: ["中国AI", "产业报告", "国产替代", "自主创新"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-006-ai-chip-landscape",
    title: "AI芯片全景报告：算力竞争的新格局",
    excerpt: "AI芯片市场竞争激烈，本报告分析技术路线、竞争格局和供应链安全。",
    date: "2026-05-03",
    tags: ["AI芯片", "算力", "竞争格局", "供应链"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-007-ai-safety-report",
    title: "AI安全报告：技术风险与治理框架",
    excerpt: "AI安全问题日益重要，本报告分析技术风险、治理框架和最佳实践。",
    date: "2026-05-02",
    tags: ["AI安全", "风险治理", "技术风险", "治理框架"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-008-ai-in-healthcare",
    title: "AI医疗报告：智慧医疗的变革之路",
    excerpt: "AI正在改变医疗行业，本报告分析AI在医疗各领域的应用进展和商业机会。",
    date: "2026-05-02",
    tags: ["AI医疗", "智慧医疗", "医疗AI", "行业报告"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-009-ai-in-finance",
    title: "AI金融报告：智能金融的创新实践",
    excerpt: "AI在金融领域广泛应用，本报告分析智能投顾、风控、客服等场景的应用。",
    date: "2026-05-01",
    tags: ["AI金融", "智能金融", "金融科技", "行业报告"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-010-ai-in-education",
    title: "AI教育报告：个性化学习的实现路径",
    excerpt: "AI正在改变教育方式，本报告分析个性化学习、智能辅导等应用的发展。",
    date: "2026-05-01",
    tags: ["AI教育", "个性化学习", "智能辅导", "教育科技"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-015-ai-investment-2025",
    title: "2025年AI投资报告：资本流向与投资机会",
    excerpt: "AI投资持续火热，本报告分析资本流向、估值变化和投资机会。",
    date: "2026-04-30",
    tags: ["AI投资", "资本流向", "投资机会", "行业报告"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-016-robotics-industry",
    title: "机器人产业报告：从工业到服务的跨越",
    excerpt: "机器人产业快速发展，本报告分析工业机器人、服务机器人和人形机器人的发展。",
    date: "2026-04-30",
    tags: ["机器人", "产业报告", "人形机器人", "服务机器人"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-017-quantum-industry",
    title: "量子产业报告：从实验室到商业化",
    excerpt: "量子技术正在走向商业化，本报告分析量子计算、量子通信的产业进展。",
    date: "2026-04-29",
    tags: ["量子产业", "量子计算", "量子通信", "前沿科技"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-018-autonomous-driving",
    title: "自动驾驶报告：从L2到L4的演进之路",
    excerpt: "自动驾驶技术持续进步，本报告分析技术路线、商业化进展和政策环境。",
    date: "2026-04-29",
    tags: ["自动驾驶", "智能汽车", "出行变革", "行业报告"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
  {
    slug: "reports-020-future-of-work",
    title: "未来工作报告：AI时代的职场变革",
    excerpt: "AI正在改变工作方式，本报告分析职场变革、技能需求和未来趋势。",
    date: "2026-04-28",
    tags: ["未来工作", "职场变革", "AI时代", "技能转型"],
    author: "BigAI",
    categoryId: "reports",
    featured: false,
  },
];

// 获取所有文章（按日期降序）
export function getAllArticles(): Article[] {
  return [...articles].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// 根据 slug 获取文章
export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

// 根据分类获取文章
export function getArticlesByCategory(categoryId: string): Article[] {
  return articles
    .filter((article) => article.categoryId === categoryId)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// 获取精选文章
export function getFeaturedArticles(): Article[] {
  return articles
    .filter((article) => article.featured)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}
